#define COL_PIXEL     64
#define ROW_PIXEL     16

#define LATCH_PIN 8
#define CLOCK_PIN 12
#define DATA_PIN 11

#define LATCH_PIN_2 7
#define CLOCK_PIN_2 10
#define DATA_PIN_2 50

#define en_74138 2
#define la_74138 3
#define lb_74138 4
#define lc_74138 5
#define ld_74138 6

#define en_74138_2 18
#define la_74138_2 17
#define lb_74138_2 16
#define lc_74138_2 15
#define ld_74138_2 9

#define SCREEN_SALIMUSTAPINBALL 0
#define SCREEN_GETREADY 1
#define SCREEN_GO 2
#define SCREEN_MULTIBALL 3
#define SCREEN_PSIT_ANIM 4
#define SCREEN_BALLLEFT 5
#define SCREEN_GAMEOVER 6
#define SCREEN_FULL 7
#define SCREEN_YOUHAVE 8
#define SCREEN_XBALLS 9
#define SCREEN_SCORE 10
#define SCREEN_BALL_INTO_HOLE 11
#define SCREEN_ROSW1 12
#define SCREEN_ROSW2 13
#define SCREEN_ROSW3 14
#define SCREEN_MIDDLE_SHOT 15
#define SCREEN_RED_SHOT 16
#define SCREEN_GREEN_SHOT 17
#define SCREEN_3BUMPERS_MODE 18
#define SCREEN_3BUMPERS_MODE_STATE 19
#define SCREEN_3BUMPERS_MODE_SUCCESS 20
#define SCREEN_GREEN_TARGET_MODE 21
#define SCREEN_GREEN_TARGET_MODE_STATE 22
#define SCREEN_ALL_GATES 23
#define SCREEN_RED_TARGET_MODE 24
#define SCREEN_RED_TARGET_MODE_STATE 25
#define SCREEN_MIDDLE_TARGET_MODE 26
#define SCREEN_MIDDLE_TARGET_MODE_STATE 27
#define SCREEN_BALL_GAME 28
#define SCREEN_BALL_GAME_INTRO 29
#define SCREEN_BUMPERS_RESULT 30
#define SCREEN_TARGETS_RESULT 31
#define SCREEN_SCORE_RESULT 33
#define SCREEN_ALL_TARGET_MODE_STATE 34
#define SCREEN_ALL_TARGET_MODE 35
#define SCREEN_PSIT_MODE_ACTIVE 36
#define SCREEN_PSIT_MODE_STATE 37
#define SCREEN_PSIT_MODE_COMPLETE 38
#define SCREEN_HIGHSCORES 39
#define SCREEN_ENTER_NAME 40
#define SCREEN_WORD_GAME 41
#define SCREEN_STARWARS_INTRO 42
#define SCREEN_STARWARS_GAME 43
#define SCREEN_STARWARS_WIN 44
#define SCREEN_STARWARS_LOST 45
#define SCREEN_STARWARS_INTRO_2 46
#define SCREEN_PLAYER_SCORES 47
#define SCREEN_PLAYER_SELECTION 48
#define SCREEN_PLAYER_WIN 49

#define PRIORITY_LOW 0
#define PRIORITY_HIGH 1

//DATA FROM MASTER
#define COUNTDOWN 0
#define BUMPER_STATUS 1
#define NB_HITS 2
#define FLIPPERS_STATE 3
#define PSIT_STATE 4
#define PLAYER_SELECTED 5

//LED MATRIX TO MASTER COMMAND
#define BALL_BOUNCE 1
#define BALL_CATCHED 2
#define GAME_IDLE 3
#define GAME_LOST 4
#define GAME_WIN 5

#define ENEMI_DESTROYED 6
#define SHIP_DESTROYED 7
#define LASER_SHOT 8


#define FONT_NORMAL 0
#define FONT_SMALL 1

